In [15]:
import pandas as pd
import FinanceDataReader as fdr

In [13]:
# KRX(Korea Exchange)에 상장된 종목들의 리스트를 가져온다.
krx = pd.read_html('https://kind.krx.co.kr/corpgeneral/corpList.do?method=download', header=0, encoding='cp949')[0]
krx = krx[['종목코드', '회사명', '업종', '상장일']]
krx = krx.rename(columns={'종목코드': 'Ticker', '회사명': 'Company'})

# 종목 코드 앞에 '0'을 붙여 6자리로 맞춥니다.
krx['Ticker'] = krx['Ticker'].apply(lambda x: str(x).zfill(6))

c:\Users\admin\Documents\GitHub\Automated-Trading-Systems\.venv\Lib\site-packages\bs4\__init__.py:228: UserWarning: You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.
  warnings.warn("You provided Unicode markup but also provided a value for from_encoding. Your from_encoding will be ignored.")

In [14]:
krx

      Ticker    Company               업종         상장일
0     095570     AJ네트웍스  산업용 기계 및 장비 임대업  2015-08-21
1     138930    BNK금융지주           기타 금융업  2011-03-30
2     155660        DSR      1차 비철금속 제조업  2013-05-15
3     294870  HDC현대산업개발           건물 건설업  2018-06-12
4     009540   HD한국조선해양           기타 금융업  1999-08-24
...      ...        ...              ...         ...
2639  446600     카이바이오텍          의약품 제조업  2022-12-23
2640  169670     코스텍시스템    특수 목적용 기계 제조업  2022-01-21
2641  318660       타임기술   소프트웨어 개발 및 공급업  2021-06-24
2642  308700        테크엔    전구 및 조명장치 제조업  2018-12-21
2643  331660   한국미라클피플사      기타 화학제품 제조업  2019-10-28

[2644 rows x 4 columns]

In [20]:
# 종목 리스팅 (종목수는 2022년 10월 25일 기준, 시장 규모 가늠 용도)
# KRX 상장회사(발행회사)목록 (가격 중심, 주식 종목) - 시가총액순
krx_lst = fdr.StockListing('KRX') # KRX: 2,663 종목(=코스피+코스닥+코넥스)

# US Market listings 미국 시장 거래소별 전종목 리스팅
sp500_lst = fdr.StockListing('S&P500') # S&P500: 503 종목  
nasdaq_lst = fdr.StockListing('NASDAQ') # 나스닥 (NASDAQ): 4,607 종목
nyse_lst = fdr.StockListing('NYSE') # 뉴욕증권거래소 (NYSE): 3,364 종목

100%|██████████| 3982/3982 [00:08<00:00, 483.69it/s]
100%|██████████| 2918/2918 [00:05<00:00, 536.45it/s]

In [22]:
nyse_lst

,Symbol,Name,Industry,IndustryCode
0,LLY,Eli Lilly and Co,제약,56201040
1,UNH,UnitedHealth Group Inc,의료 관리,56102020
2,V,Visa Inc,온라인 서비스,57201030
3,TSM,Taiwan Semiconductor Manufacturing Co Ltd ADR,반도체,57101010
4,XOM,Exxon Mobil Corp,"오일, 가스 정제 및 마케팅",50102030
...,...,...,...,...
2913,KMPB,Kemper 5 875 Fixed Rate Reset Junior Subordina...,손해보험,55301020
2914,MMM WD,3M Co,소비재 대기업,54401010
2915,RZC,Reinsurance Group of America 7 125 Fixed Rate ...,재보험,55301050
2916,NSA PR B,National Storage Affiliates 6 000 Cumulative ...,특수 REITs,60102040
2917,PMTU,PennyMac Mortgage Investment 8 50 Senior Notes...,특수 REITs,60102040